### ISSUE TITLE
Is not a real issue but read please

### ISSUE THREAD

**Issue by ElHave247** [LokeYourC3PH/Extremely-Efficient-Structures#5]
Hello i see you was working to add yuzu support to ryusak maybe you want to take a look to my profile, and get the pieces you miss to start adding support. You can delete this issue, thanks for read.

**Comment by LokeYourC3PH** [comment]
Howdy! Yea I was planning on it, but then figured two things:

1: RyuSAK was built on a shit foundation, and I was facing issues upon issues trying to even just compile the base version, something I gave up on in the end.

2: Yuzu was built by arrogant retards, and I want no further involvement in anything Yuzu ever again, just like a huge part of the community. And if you ever speak to that Fernando cunt from Yuzu, tell him to go fuck himself.

Yeah that's it, sorry but won't happen. I had already begun and made good progress, and adding support wasn't difficult or anything, but I stopped for those two reasons.

**Comment by ElHave247** [comment]
Build ryusak is super easy, i can help you to do, is more im going to upload directly modified ryusak to get more friendly to setup web connection. But there is full web backup on my profile, i dont know about yuzu staff, and i dont want to speak with any staff, because most of then on most of things are stupid arrogant people, with puritanism morality in the sky. But ithinked like you it is a good feature for the community and more when im doing to ryusak can run full offline, without need to go to ecchibicionist server, and depend if he is trigerred or no and he close or no service in any angry he get.  It was going to be a cool feature return yuzu support to their users. Personaly i have ryu and yuzu and both can run at sound velocity without shaders so i dont have any propblem, but i think on the rest.

**Comment by LokeYourC3PH** [comment]
Sorry forgot about this. Right so, as I said, Yuzu is dead for me, I stand by my principles. Adding Yuzu support is truly easy, but I have no intention of ever doing anything Yuzu ever again.

The thing with the server is a different issue that I'll gladly work on to fix at some point, but Yuzu cannot get hit with an DMCA quick enough imo.
